name: BETA Release
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: 'Build and release'
    runs-on: ubuntu-latest
    environment:
      name: Beta

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm ci

      - name: Prepare BETA
        run: node scripts/beta-release.js $GITHUB_RUN_ID

      - name: Run localization sync
        run: npm run localization:sync
        env:
          TRANSLATION_API_KEY: ${{ secrets.TRANSLATION_API_KEY }}
          TRANSLATION_API_LOCATION: ${{ secrets.TRANSLATION_API_LOCATION }}
          TRANSLATION_API_URL: ${{ secrets.TRANSLATION_API_URL }}

      - name: Publish
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }} --baseImagesUrl https://raw.githubusercontent.com/estruyf/vscode-front-matter/dev

      - name: Publish to open-vsx.org
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_PAT }}
